/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kkpkremes;
import kkpkremes.Koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kkpkremes.MenuUtama;
/**
 *
 * @author maria
 */
public class SMSInbox extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    Connection conn;
    Statement stat;
    ResultSet res;
    
    private String cariBy="", kriteria="";
    Object[] Baris={"NO. INBOX","No HANDPHONE","WAKTU SMS","PESAN"};
    DefaultTableModel tabmode = new DefaultTableModel(null, Baris);

    /**
     * Creates new form SMSInbox
     */
    public SMSInbox(MenuUtama mUtama) {
        initComponents();
        this.mUtama = mUtama;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
        datatabel();
        setTabel(tblInbox, new int[]{100,150,150,300});
        isiComboCari();
    }
    
    public void bersihTable() {
        int row = tblInbox.getRowCount() - 1;
        while (row >= 0) {
            tabmode.removeRow(row);
            row--;
        }
    }
    
     public void setTabel (javax.swing.JTable tb, int lebar[]) {
        tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
        int kolom = tb.getColumnCount();
        for (int i=0; i<kolom; i++) {
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(18);
        }
    }
    
    private void isiComboCari(){
        cmbCari.addItem("NO. INBOX");
        cmbCari.addItem("NO HANDPHONE");
        cmbCari.addItem("WAKTU SMS");
        cmbCari.addItem("PESAN");
    }
    
    public void datatabel(){
        tblInbox.setModel(tabmode);
        String sql = "SELECT * FROM inbox";
        try {
             Koneksi konek = new Koneksi();
            Connection con = konek.bukaKoneksi();
            Statement st = con.createStatement();
            res=st.executeQuery(sql);
            while(res.next()){
                String a = res.getString("no_inbox");
                String b = res.getString("no_hp");
                String c = res.getString("waktu");
                String d = res.getString("pesan");
                String[] data = {a,b,c,d};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
        }
    
    public void CariData(){
        dapatData();
        //String abc = txtCari.getText();
        tblInbox.setModel(tabmode);
       String sql = "SELECT * FROM inbox WHERE "+cariBy+" LIKE '%"+kriteria+"%'";
        try {
             Koneksi konek = new Koneksi();
            Connection con = konek.bukaKoneksi();
            Statement st = con.createStatement();
            stat = con.createStatement();
            res=stat.executeQuery(sql);
            while(res.next()){
                String a = res.getString("no_inbox");
                String b = res.getString("no_hp");
                String c = res.getString("waktu");
                String d = res.getString("pesan");
                String[] data = {a,b,c,d};
                tabmode.addRow(data);
            }
            conn.close();
        } catch (Exception e) {
        }
    }
    
    private void dapatData(){
         switch(cmbCari.getSelectedIndex()){
            case 0 : cariBy = "no_inbox"; break;
            case 1 : cariBy = "no_hp"; break;
            case 2 : cariBy = "waktu"; break;
            case 3 : cariBy = "pesan"; break;
            default : cariBy = "no_inbox";
        }
         
        kriteria = txtCari.getText().trim();     
    }
    
     public void bersih() {
        txtCari.setText("");
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox();
        txtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInbox = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Cari");

        cmbCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Pelanggan" }));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblInbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Inbox", "No Handphone", "Waktu", "Pesan"
            }
        ));
        jScrollPane1.setViewportView(tblInbox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersihTable();
        CariData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtCari.setText("");
        bersihTable();
        CariData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
if(evt.getKeyCode() ==  evt.VK_ENTER) {
            bersihTable();
            CariData();
        }
    }//GEN-LAST:event_txtCariKeyPressed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
bersihTable();
CariData();
    }//GEN-LAST:event_txtCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInbox;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
