/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kkpkremes;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import kkpkremes.MenuUtama;

public class SMSKomplain extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    Connection conn;
    Statement stat;
    ResultSet res;
    private String cariBy="", kriteria="";
    Object[] Baris={"NO.Komplain","Kode Pelanggan","Tanggal Komplain","No Handphone","Isi Komplain"};
    DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
    /**
     * Creates new form SMSKomplain
     */
    public SMSKomplain(MenuUtama mUtama) {
        initComponents();
        this.mUtama = mUtama;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
        datatabel();
        setTabel(tblKomplain, new int[]{100,150,150,150,500});
        isiComboCari();
    }

public void bersihTable() {
        int row = tblKomplain.getRowCount() - 1;
        while (row >= 0) {
            tabmode.removeRow(row);
            row--;
        }
    }
    
    public void setTabel (javax.swing.JTable tb, int lebar[]) {
        tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
        int kolom = tb.getColumnCount();
        for (int i=0; i<kolom; i++) {
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(18);
        }
    }
    
    private void isiComboCari(){
        cmbCari.addItem("NO.KOMPLAIN");
        cmbCari.addItem("KODE PELANGGAN");
        cmbCari.addItem("TANGGAL KOMPLAIN");
        cmbCari.addItem("NO HANDPHONE");
        cmbCari.addItem("ISI KOMPLAIN");
    }
    
    public void datatabel(){
        tblKomplain.setModel(tabmode);
        String sql = "SELECT * FROM komplain";
        try {
             Koneksi konek = new Koneksi();
            Connection con = konek.bukaKoneksi();
            Statement st = con.createStatement();
            res=st.executeQuery(sql);
            while(res.next()){
                String a = res.getString("no_komplain");
                String b = res.getString("kd_pelanggan");
                String c = res.getString("tgl_komplain");
                String d = res.getString("no_hp");
                String e = res.getString("isi_komplain");
                String[] data = {a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
        }
    
    private void dapatData(){
         switch(cmbCari.getSelectedIndex()){
            case 0 : cariBy = "no_komplain"; break;
            case 1 : cariBy = "kd_pelanggan"; break;
            case 2 : cariBy = "tgl_komplain"; break;                
            case 3 : cariBy = "no_hp"; break;
            case 4 : cariBy = "isi_komplain"; break;
            default : cariBy = "no_komplain";
        }
         
        kriteria = txtCari.getText().trim();     
    }
 public void CariData(){
        dapatData();
        //String abc = txtCari.getText();
        tblKomplain.setModel(tabmode);
       String sql = "SELECT * FROM komplain WHERE "+cariBy+" LIKE '%"+kriteria+"%'";
        try {
             Koneksi konek = new Koneksi();
            Connection con = konek.bukaKoneksi();
            Statement st = con.createStatement();
            stat = con.createStatement();
            res=stat.executeQuery(sql);
            while(res.next()){
                String a = res.getString("no_komplain");
                String b = res.getString("kd_pelanggan");
                String c = res.getString("tgl_komplain");
                String d = res.getString("no_hp");
                String e = res.getString("isi_komplain");
                String[] data = {a,b,c,d,e};
                tabmode.addRow(data);
            }
            conn.close();
        } catch (Exception e) {
        }
    }   
    
    public void bersih() {
        txtCari.setText("");
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKomplain = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Cari");

        btnCari.setText("Cari");

        btnBatal.setText("Batal");

        tblKomplain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.Komplain", "Kode Pelanggan", "Tanggal Komplain", "No Handphone", "Isi Komplain"
            }
        ));
        jScrollPane1.setViewportView(tblKomplain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(btnBatal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JComboBox cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKomplain;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
