/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kkpkremes;

import server.Crud;
import server.Validasi;
import server.libSms;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kkpkremes.Koneksi;
import kkpkremes.MenuUtama;


/**
 *
 * @author maria
 */
public class SMSServer extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
//    libSms at = new libSms();
    Crud crud = new Crud();
    Validasi validasi = new Validasi();
    private static int PERHALAMAN = 120;
    private boolean flagKoneksi=false;
    private String Pesan="", nohp="";
    public javax.swing.DefaultListModel listModel = new javax.swing.DefaultListModel();
    public javax.swing.DefaultListModel listModellog;
    DefaultTableModel tabMode;
    boolean allow=true;
    /**
     * Creates new form SMSServer
     */
    public SMSServer(MenuUtama mUtama) {
        initComponents();
//        listModellog = at.listmodellog;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
        ListGroupPenerima.setModel(listModel);
//        try {
//            setListGroupPenerima();            
//        } catch (Exception e){
//            e.printStackTrace();
//        }
       String[] header     = {"No. Handphone","Kode Pelanggan","Nama Pelanggan", "Alamat"};
        tabMode = new DefaultTableModel(null,header);
        tblkontakpenerima.setModel(tabMode);
//        try {
//            isiTableKontak();
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
        setTabel(tblkontakpenerima,new int[]{130,130,200,300});
        isiBaudRate();
        deteksiPort();
        kondisiAwal();        
//        ListLog.setModel(listModellog);
        
    }

 private void setListGroupPenerima() throws SQLException {
        java.sql.ResultSet rs = crud.listGroup();
        int index = 0;
        while (rs.next()) {
            String nm_group = rs.getString("nama_group");
            listModel.add(index, nm_group);
            index++;
        }
    }    
    
public void setTabel (javax.swing.JTable tb, int lebar[]) {
        tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
        int kolom = tb.getColumnCount();
        for (int i=0; i<kolom; i++) {
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(18);
        }
    }
private void isiTableKontak() throws SQLException{
            hapusTabel();
        java.sql.ResultSet rs = crud.dataTablePelanggan();
        while (rs.next()){
            String no_hp = rs.getString("no_hp");
            String kdplg = rs.getString("kd_pelanggan");
            String nmplg = rs.getString("nama_pelanggan");            
            String alamat = rs.getString("alamat");
            
            String[] data   = {no_hp,kdplg,nmplg,alamat};
            tabMode.addRow(data);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPORT = new javax.swing.JComboBox();
        cmbBAUDRATE = new javax.swing.JComboBox();
        btnCONNECT = new javax.swing.JButton();
        btnDISCONNECT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblStatusKoneksi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpesan = new javax.swing.JTextArea();
        btnBatal = new javax.swing.JButton();
        btnKirim = new javax.swing.JButton();
        lblkarakter = new javax.swing.JLabel();
        lblJmlKarakter = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListLog = new javax.swing.JList();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListGroupPenerima = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblkontakpenerima = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Server SMS"));

        jLabel2.setText("PORT");

        jLabel3.setText("BAUD RATE");

        cmbPORT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT" }));

        cmbBAUDRATE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT" }));

        btnCONNECT.setText("CONNECT");
        btnCONNECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCONNECTActionPerformed(evt);
            }
        });

        btnDISCONNECT.setText("DISCONNECT");
        btnDISCONNECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDISCONNECTActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        lblStatusKoneksi.setText("Tidak ada koneksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDISCONNECT)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPORT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBAUDRATE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCONNECT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusKoneksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPORT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbBAUDRATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCONNECT)
                .addGap(18, 18, 18)
                .addComponent(btnDISCONNECT)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblStatusKoneksi))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kontrol Broadcast"));

        jLabel6.setText("Isi pesan broadcast");

        txtpesan.setColumns(20);
        txtpesan.setRows(5);
        txtpesan.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtpesanCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txtpesan);

        btnBatal.setText("batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKirim.setText("Kirim");
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });

        lblkarakter.setText("Karakter/Halaman :");

        lblJmlKarakter.setText("0/1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblkarakter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblJmlKarakter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBatal)
                            .addGap(56, 56, 56)
                            .addComponent(btnKirim))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkarakter)
                    .addComponent(lblJmlKarakter)
                    .addComponent(btnKirim)
                    .addComponent(btnBatal))
                .addGap(22, 22, 22))
        );

        ListLog.setBackground(new java.awt.Color(255, 255, 0));
        jScrollPane3.setViewportView(ListLog);

        jTabbedPane1.addTab("List Proses Server", jScrollPane3);

        ListGroupPenerima.setBackground(new java.awt.Color(255, 255, 0));
        ListGroupPenerima.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "0000" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListGroupPenerima.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane2.setViewportView(ListGroupPenerima);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Group", jPanel5);

        tblkontakpenerima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Pelanggan", "Nama Pelanggan", "No Handphone", "Alamat"
            }
        ));
        jScrollPane4.setViewportView(tblkontakpenerima);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        jTabbedPane3.addTab("Kontak", jPanel6);

        jTabbedPane1.addTab("Data Kontak Pelanggan", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCONNECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCONNECTActionPerformed
        // TODO add your handling code here:
        Koneksi();
    }//GEN-LAST:event_btnCONNECTActionPerformed

    private void btnDISCONNECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDISCONNECTActionPerformed
        // TODO add your handling code here:
        
        at.tutupPort();
        kondisiAwal();
    }//GEN-LAST:event_btnDISCONNECTActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        txtpesan.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        // TODO add your handling code here:
        if (jTabbedPane3.getSelectedIndex()==0) {
            Vector penerima = crud.listKontakGroup(ListGroupPenerima.getSelectedValue().toString());
            for (int i=0; i < penerima.size(); i++) {
                at.prosesKirimBroadcast(penerima.get(i).toString(), txtpesan.getText().toString());
            }            
            javax.swing.JOptionPane.showMessageDialog(this, "Broadcast Selesai");
        } else {
            int row = tblkontakpenerima.getSelectedRow();            
            at.prosesKirimBroadcast(tabMode.getValueAt(row, 0).toString(), txtpesan.getText().toString());            
        }
         
    }//GEN-LAST:event_btnKirimActionPerformed

    private void txtpesanCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtpesanCaretUpdate
       setKarakter();
    }//GEN-LAST:event_txtpesanCaretUpdate
private void setKarakter(){
        int panjang  = txtpesan.getText().length();
        int perhlman = PERHALAMAN ;
        int x   = panjang / perhlman;
        int y   = panjang % perhlman;
        String karakter = "0";
        String halaman  = "1";
        
        if(panjang>0){
            if(y>0){
                karakter    = String.valueOf(y);
                halaman     = String.valueOf(x+1);
            }
            else {
                karakter    = String.valueOf(perhlman);
                halaman     = String.valueOf(x);
            }
        }
        
        lblJmlKarakter.setText(karakter+" / "+halaman);
    }
    
     private void keluar(){
        if(flagKoneksi){
            JOptionPane.showMessageDialog(null, "Koneksi Ke Alat Belum Ditutup,"+"Harap Koneksi Tutup Terlebih Dahulu", "Error",0);
            this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        }else{
            dispose();
        }
    }
    
    
    private void kondisiAwal(){
        btnCONNECT.setEnabled(true);
        btnDISCONNECT.setEnabled(false);
        btnKirim.setEnabled(false);
        txtpesan.setText(""); 
        lblStatusKoneksi.setText("Tidak Terkoneksi");
        
    }
    
    private void isiBaudRate(){
        cmbBAUDRATE.removeAllItems();
    	cmbBAUDRATE.addItem("4800");
    	cmbBAUDRATE.addItem("9600");
    	cmbBAUDRATE.addItem("19200");
    	cmbBAUDRATE.addItem("38400");
    	cmbBAUDRATE.addItem("57600");
    	cmbBAUDRATE.setSelectedIndex(1);
    }
    
    
    
    private void hapusTabel(){
        int brs = tabMode.getRowCount();
        for(int i=0;i<brs;i++){
            tabMode.removeRow(0);
        }
    }
    
   
    
    private void deteksiPort(){
         Thread t = new Thread() {
            public void run() {
                cmbPORT.removeAllItems();
                // Mencari daftar port-port yang tersedia
                java.util.Enumeration portList = gnu.io.CommPortIdentifier.getPortIdentifiers();
                java.util.Vector tampung=new java.util.Vector();
                while (portList.hasMoreElements()) {
                        // Mengambil nilai-nilai port yang ditemukan
                        gnu.io.CommPortIdentifier portId = (gnu.io.CommPortIdentifier) portList.nextElement();
                        // Hanya Port Serial yang diambil
                        if (portId.getPortType() == gnu.io.CommPortIdentifier.PORT_SERIAL) {
                            cmbPORT.addItem(portId.getName().toString());                            
                        } // Akhir if port getPortType
                } // Akhir while
             }
          };
        t.start();
    }
    
    public void setList(String isi, int delay){
        listModellog = at.listmodellog;
        ListLog.setSelectionInterval(at.indexlist, at.indexlist);
        ListLog.setSelectedIndex(at.indexlist);
        ListLog.ensureIndexIsVisible(at.indexlist);
        try{
            Thread.sleep(delay);
        }catch(InterruptedException ex){
            ex.printStackTrace();
        }
        ++at.indexlist;
        ListLog.requestFocus();
    }
    
    private void Koneksi() {        
        try {
            btnCONNECT.setEnabled(false);
            at.setPort(cmbPORT.getSelectedItem().toString());
            at.bukaPort();
            btnDISCONNECT.setEnabled(true);
            btnKirim.setEnabled(true);
            lblStatusKoneksi.setText("Terkoneksi");
        } catch (Exception e) {
            System.out.println("Gagal Melakukan Proses Koneksi !"+e);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListGroupPenerima;
    private javax.swing.JList ListLog;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCONNECT;
    private javax.swing.JButton btnDISCONNECT;
    private javax.swing.JButton btnKirim;
    private javax.swing.JComboBox cmbBAUDRATE;
    private javax.swing.JComboBox cmbPORT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblJmlKarakter;
    private javax.swing.JLabel lblStatusKoneksi;
    private javax.swing.JLabel lblkarakter;
    private javax.swing.JTable tblkontakpenerima;
    private javax.swing.JTextArea txtpesan;
    // End of variables declaration//GEN-END:variables
}

